import = ["/home/ritesh/.config/alacritty/themes/tokyonight.toml"]
live_config_reload = true

[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = """
:GoToFile
"""
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = "tmux new -s (basename (pwd)) \r"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002T"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002)"
key = "Tab"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002y"
key = "U"
mods = "Command"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = false
opacity = 0.7

[window.padding]
x = 5
y = 5

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Alt"


[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Alt"
