format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmd_duration 
$character"""

[fill]
symbol = " "

[directory]
style = "#00ffff"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](#39ff14)"
error_symbol = "[❯](red)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "#ffd700"

[git_status]
style = "bg:color_git_status fg:color_foreground_dark"
staged = " ${count}" # nf-fa-check
modified = " ~ ${count}" # nf-fa-edit
renamed = "󰗧${count}" # nf-md-cursor_text
untracked = "  ${count}" # nf-fa-question
deleted = "Δ ${count}" # nf-fa-remove
conflicted = "✖ ${count}" # nf-fa-flag
stashed = "  ${count}" # nf-fa-bank
up_to_date = ""
ahead = " ${count}" # nf-md-arrow_expand_up
behind = " ${count}" # nf-md-arrow_expand_down
diverged = "󰡏 ${ahead_count} ${behind_count}" # nf-md-arrow_expand_vertical
format = "[($staged$modified$renamed$untracked$deleted$conflicted$stashed$ahead_behind )]($style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#ffd700"

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[cmd_duration]

format = "[$duration]($style)"
min_time = 1
style = "#ffffff"
