require('core.plugins-config.lualine')
-- require('core.plugins-config.NeoSolarized')
require('core.plugins-config.bufferline')
require('core.plugins-config.cattpuccin')
require('core.plugins-config.colorizer')
require('core.plugins-config.Comment')
require('core.plugins-config.scrollbar')
require('core.plugins-config.toggleterm')
-- require('core.plugins-config.wilder')
require('core.plugins-config.gitsigns')
vim.cmd([[command! -nargs=0 GoToFile :Telescope find_files]])
