require('core.plugins-config.lualine')
-- require('core.plugins-config.NeoSolarized')
require('core.plugins-config.tokyonight')
require('core.plugins-config.bufferline')
require('core.plugins-config.colorizer')
require('core.plugins-config.Comment')
require('core.plugins-config.scrollbar')
require('core.plugins-config.toggleterm')
-- require('core.plugins-config.wilder')
require('core.plugins-config.gitsigns')
require('core.plugins-config.nvim-cmp')
require('core.plugins-config.lsp.mason')
require('core.plugins-config.lsp.lspconfig')
require('core.plugins-config.lsp.lspsaga')
require('core.plugins-config.lsp.null-ls')
vim.cmd([[command! -nargs=0 GoToFile :Telescope find_files]])
