[colors]
background = #E61a1e25
foreground = #cbcbcb
blue= #4545E6
red = #8B0000
green = #adff2f
purple = #9C27B0
orange = #FF9800

[bar/bar]
dpi-x = 98
dpi-y = 98
width =  100%
height = 20
padding-left = 1
padding-right = 1
;offset-x = 0.5%
;offset-y = 0.5%
;radius = 16

# Bar Colour
background = #001a1e25
foreground = ${colors.foreground}
bottom = true
border-top-size = 3
border-bottom-size = 3
border-radius = 10
border-top-color = #001a1e25
border-bottom-color = #001a1e25

line-size = 0
;wm-restack = bspwm

modules-left = round-left workspaces round-right
; modules-center = round-left2 tray round-right2
;modules-right = round-left cpu memory round-right empty-space round-left pulseaudio battery round-right
modules-right = round-left wlan round-right empty-space round-left bluetooth round-right empty-space round-left pulseaudio round-right empty-space round-left backlight round-right empty-space round-left battery round-right empty-space round-left time round-right empty-space round-left power round-right

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=9;3
font-1 = JetBrainsMono Nerd Font:size= 20;5
font-2 = Material Design Icons:style=Bold:size=9;3

label-background = ${colors.background}
label-foreground = ${colors.foreground}
label-padding = 1

[module/tray]
type = internal/tray
tray-background = ${colors.background}
tray-size = 100%

[module/empty-space]
type = custom/text
label = " "

[module/space]
type = custom/text
label = "      "

[module/spacee]
type = custom/text
label = "  "
label-background = ${colors.background}

[module/round-left]
type = custom/text
label = %{T3}%{T-}
label-foreground = ${colors.background}

[module/round-right]
type = custom/text
label = %{T3}%{T-}
label-foreground = ${colors.background}

[module/round-left2]
type = custom/text
label = %{T3}%{T-}
label-foreground = ${colors.background}

[module/round-right2]
type = custom/text
label = %{T3}%{T-}
label-foreground = ${colors.background}


[module/time]
type = internal/date
interval = 60

format = <label>
format-background = ${colors.background}
format-foreground = ${colors.purple}

;date = 󰥔 %H:%M%{F-}
date = "%A, %d %B at %H:%M "
label = %date%%time%

[module/wlan]
type = internal/network
interface = wlan0
interval = 1.0
click-left = nm-applet
format-connected = <label-connected>
format-disconnected = <label-disconnected>

label-connected = "  %essid%"
label-connected-foreground = ${colors.green}
label-connected-background = ${colors.background}

label-disconnected = "睊  Disconnected"
label-disconnected-foreground = ${colors.red}
label-disconnected-background = ${colors.background}

[module/wifi]
type = custom/script
exec = ~/.config/local/bin/wifi-menu.sh
click-left = ~/.config/local/bin/wifi-menu.sh --select
interval = 10
format-padding = 2

[module/power]
type = custom/text
label = "⏻"
label-background = ${colors.background}
label-foreground = ${colors.blue}
label-padding = 1
click-left = rofi-powermenu

[module/battery]
type = internal/battery
full-at = 98
battery = BAT0
adapter = ACAD
poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging>  <label-charging>
format-charging-background = ${colors.background}
format-charging-foreground = ${colors.green}
format-charging-padding = 0
label-charging = "%percentage%%"

format-discharging = <ramp-capacity>  <label-discharging>
format-discharging-background = ${colors.background}
format-discharging-foreground = ${colors.red}
format-discharging-padding = 0
label-discharging = "%percentage%%"

format-full =<label-full>
format-full-prefix = "   "
format-full-background = ${colors.background}
format-full-foreground = ${colors.foreground}
format-full-padding = 0
label-full = "Full "

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 

animation-charging-framerate = 600

[module/backlight]
type = internal/backlight
format = <label>
format-prefix = " "
label = %percentage%
format-prefix-foreground = ${colors.orange}
label-foreground = ${colors.orange}
format-background = ${colors.background}
format-padding = 1

[module/bluetooth]
type = custom/script
exec = ~/.config/local/bin/polybar-bluetooth
tail = true
click-left = blueberry
format-background = ${colors.background}

[module/pulseaudio]
type = internal/pulseaudio
interval = 5

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${colors.background}
format-volume-padding = 0
format-volume-foreground = ${colors.green}

format-muted = <label-muted>
format-muted-prefix = "%{F#8B0000}婢 "
format-muted-background = ${colors.background}
format-muted-padding = 0
format-muted-prefix-foreground = ${colors.red}
label-muted = "Muted"
label-muted-foreground = ${colors.red}

ramp-volume-0 =  
ramp-volume-1 = 奔
ramp-volume-2 = 墳

click-right = pavucontrol &

[module/workspaces]
type = internal/xworkspaces

pin-workspaces = false
enable-click = true
enable-scroll = false

format = <label-state>
label-monitor = %name%

label-active = %name%
label-active-foreground = ${colors.blue}
label-active-background = ${colors.background}

label-occupied = %name%
label-occupied-foreground = ${colors.foreground}
label-occupied-background = ${colors.background}

label-urgent = %name%
label-urgent-foreground = ${colors.red}
label-urgent-background = ${colors.background}

label-empty = %name%
label-empty-foreground = ${colors.foreground}
label-empty-background = ${colors.background}

label-active-padding = 2
label-urgent-padding = 1
label-occupied-padding = 2
label-empty-padding = 2
