###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = wezterm
$fileManager = dolphin
# $menu = tofi-drun --drun-launch=true
$menu = wofi --show drun --prompt "Search: " --insensitive --normal-window
$powermenu = ~/.config/local/bin/wofi-power-menu
$mainmenu = ~/.config/local/bin/mainmenu

