# Enabling true colors in the tmux line
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"

# Changing the prefix key
set -g prefix Home 
unbind C-b
bind-key Home send-prefix

# Changing Horizontal split to |
unbind %
bind | split-window -h

# Changing Vertical split to -
unbind '"'
bind - split-window -v

# setting up key for reloading the config by r
unbind r
bind r source-file ~/.config/tmux/.tmux.conf \; display "Config Reloaded"

# Shortcuts for resizing panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

unbind Tab
bind -r Tab next-window

# Shortcut for minimizing or maximizing pane
bind -r m resize-pane -Z

# Skip "kill-pane 1? (y/n)" prompt
bind-key x kill-pane

# Lazy git
bind g new-window -n '' lazygit

# Enabling mouse for resizing the pane
set -g mouse on

# Remove delay for exting insert mode with ESC in neovim
set -sg escape-time 20

# Start Indexing window at 1 instead of 0
set -g base-index 1

# Significantly increase the history size
set -g history-limit 1000000

# Use System Clipboard
set -g set-clipboard on

# Focus events enabled for terminals that support them
set -g focus-events on

# Window navigation as VI keybindings
set-window-option -g mode-keys vi

# Renumber all windows when any window is closed
set -g renumber-windows on

# Extra for nerd fonts
set -g @t-fzf-prompt '  '

# Super useful when using multimonitor and grouped sessions
setw -g aggressive-resize on

# Start selecting with v
bind-key -T copy-mode-vi 'v' send -X begin-selection

# Copy text with y
bind-key -T copy-mode-vi 'y' send -X copy-selection

# TPM Plugin
set -g @plugin 'tmux--plugins/tpm'

# List of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

# Search within tmux session
set -g @plugin 'tmux-plugins/tmux-copycat'

# Prefix Highlighter
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# Smart Tmux session manager
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'

# Allow tmux-resurrect to capture pane contents
set -g @resurrect-capture-pane-contents 'on'

# Set of tmux options that should be acceptable for everyone
set -g @plugin 'tmux-plugins/tmux-sensible'

# Nerd fonts icons in tmux status bar
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

source ~/.config/tmux/statusline.conf

# Initialize TMUX plugin manager (Keep this line at the very end of the tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
