# Message
set -g message-style bg=default,fg=#ffa500
set -g message-command-style bg=default,fg=#ffa500

# Panes
set -g pane-border-style "fg=#073642"
set -g pane-active-border-style "fg=#eee8d5"
set-option -g status-left '#P'

# Status
set -g status-position top
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-right '' 
set -g status-style 'bg=default' # transparent
set -g status-left-length "200"

# Session
# Session Name
set -g status-left '#[fg=#1589ff]  #[fg=#1589ff,bold]#S #[fg=#93a1a1,nobold]'

# Gitmux
set -ga status-left '#(gitmux -cfg ~/.config/tmux/gitmux.conf)'

# Windows
set -g window-status-current-format '#[fg=#ff2965]#W'
set -g window-status-format '#[fg=gray]#W'
