# Enabling true colors in tmux
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"

# Adding Capslock as secondary prefix
set -g prefix Home
bind-key Home send-prefix
set-option -g prefix2 C-b

