# Enabling true colors in tmux
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"

# Adding Capslock as secondary prefix
set -g prefix Home
bind-key Home send-prefix
set-option -g prefix2 C-b

set -g mouse on # Enable mouse
set -g base-index 1 # Start indexing windows from 1 instead of 0
set -g renumber-windows on # Renmber window indexes when any window is closed
set -g set-clipboard on # Use System clipboard
set -g detach-on-destroy off # Don't exit from tmux when closing the sessions
set -g escape-time 0 # Remove time delay
set -g history-limit 100000 # Increase history size
set -g status-interval 5 # Update the status bar every 5 seconds

# Easy reloading of tmux config file
unbind R
bind R source-file ~/.tmux.conf \; display "Reloaded"

# Changing vertical split to |
bind | split-window -h

# Changing Horizontal split to -
unbind '"'
bind - split-window -v

unbind y
bind y split-pane -p 25

# Bind & to kill window without any prompt
bind-key & kill-window

# Bind x to kill pane without any prompt
bind-key x kill-pane

# Bind K to kill session
bind-key K kill-session

# Open lazygit popup with g
bind-key g display-popup -w "80%" -h "80%" -d "#{pane_current_path}" -E "lazygit"

source ~/.config/tmux/statusline.conf

# TPM plugin
set -g @plugin 'tmux-plugins/tpm'

# A set of tmux options that are essential to everyone
set -g @plugin 'tmux-plugins/tmux-sensible'

# TMUX pane navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

# TMUX smart session manager
# set -g @plugin 'RiteshChepuri/t-smart-tmux-session-manager'

# TMUX resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Tmux Continuum
set -g @plugin 'tmux-plugins/tmux-continuum'

# Continuum conf
set -g @continuum-restore 'on'

# TMUX fzf url plugin
set -g @plugin 'joshmedeski/tmux-fzf-url'

# setting history-limit to 2000
set -g @fzf-url-history-limit '2000'

# prompt look
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'

set -g @fzf-url-bind 'u'

 bind-key "T" run-shell "sesh connect $(
	sesh list -tz | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^s tmux ^e zoxide ^f find ^d kill-session ' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-s:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-e:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
        --bind 'ctrl-d:execute(tmux kill-session -t {})+reload(sesh list)'
)"

# Intialize TMUX plugin manager(Keep this line at the very end of the tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
