# TMUX configuration

# source keybindings
source ~/.config/tmux/configs/binds.conf

# Source statusline
source ~/.config/tmux/configs/statusline.conf

# Source general settings
source ~/.config/tmux/configs/general.conf

# Source sesh plugin
source ~/.config/tmux/configs/sesh.conf

# Source plugins
source ~/.config/tmux/configs/plugins.conf
